# Generated by Django 5.1.3 on 2024-11-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregate_company', '0002_node_employee_address_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
